name: Main

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19]
        pnpm-version: [8]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}
      - name: Cache pnpm
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-
      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: |
            node_modules
            docs/node_modules
            examples/**/node_modules
            packages/**/node_modules
            packages/**/dist
            references/packages/**/node_modules
          key: modules-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: pnpm i
      - name: Link Dependencies
        if: steps.cache-node-modules.outputs.cache-hit == 'true'
        run: pnpm dev

  lint:
    name: Lint
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19]
        pnpm-version: [8]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            docs/node_modules
            examples/**/node_modules
            packages/**/node_modules
            packages/**/dist
            references/packages/**/node_modules
          key: modules-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Check types
        run: pnpm typecheck
      - name: Lint & format code
        run: pnpm lint:fix && pnpm lint:format packages
      - name: Commit
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git add .
          if [ -z "$(git status --porcelain)" ]; then
            echo "no formatting changed"
            exit 0
          fi
          git commit -m "chore: format"
          git push
          echo "pushed formatting changes https://github.com/$GITHUB_REPOSITORY/commit/$(git rev-parse HEAD)"

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19]
        pnpm-version: [8]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            docs/node_modules
            examples/**/node_modules
            packages/**/node_modules
            packages/**/dist
            references/packages/**/node_modules
          key: modules-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Build
        run: pnpm build

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    env:
      ANVIL_BLOCK_NUMBER: 15578840
    strategy:
      matrix:
        node-version: [19]
        pnpm-version: [8]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            docs/node_modules
            examples/**/node_modules
            packages/**/node_modules
            packages/**/dist
            references/packages/**/node_modules
          key: modules-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Cache Anvil
        uses: 'actions/cache@v3'
        with:
          path: ~/.foundry/cache/rpc/**/${{ env.ANVIL_BLOCK_NUMBER }}
          key: foundry-anvil-${{ env.ANVIL_BLOCK_NUMBER }}
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
      - name: Install Anvil
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Launch Anvil
        run: anvil --fork-url $ANVIL_FORK_URL --fork-block-number $ANVIL_BLOCK_NUMBER &
        env:
          ANVIL_FORK_URL: ${{ secrets.ANVIL_FORK_URL }}
      - name: Test `@wagmi/cli`, `@wagmi/core`, and `wagmi`
        run: pnpm test:coverage
      - name: Test types
        run: pnpm test:typecheck
      # Need to shutdown Anvil so cache gets created
      - name: Shutdown Anvil
        run: pkill -2 anvil
