name: Release (canary)

on:
  push:
    branches:
      - 'main'
    paths:
      - 'packages/**/src/**'
      - '.github/workflows/release-canary.yml'
  workflow_dispatch:

jobs:
  build_and_publish:
    name: Release (canary)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
        pnpm-version: [7]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        run: pnpm i --ignore-scripts

      - name: Build
        run: pnpm build

      - name: Set version
        run: |
          npm --no-git-tag-version version minor
          npm --no-git-tag-version version $(npm pkg get version | sed 's/"//g')-$(git branch --show-current | tr -cs '[:alnum:]-' '-' | tr '[:upper:]' '[:lower:]' | sed 's/-$//').$(date +'%Y%m%dT%H%M%S')

      - id: publish
        name: Publish to npm
        run: npm publish --tag $(git branch --show-current | tr -cs '[:alnum:]-' '-' | tr '[:upper:]' '[:lower:]' | sed 's/-$//')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


